// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBg05bA6RK2Zo8LUWQmkiMiNUpba8UG_8Q',
    appId: '1:284707235547:web:462b79cb261f011946cefe',
    messagingSenderId: '284707235547',
    projectId: 'netflix-clone-89f02',
    authDomain: 'netflix-clone-89f02.firebaseapp.com',
    storageBucket: 'netflix-clone-89f02.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPKk-yps4pePKdKSoZacsa7f2xf8Rdd-k',
    appId: '1:284707235547:android:8a87089b85ca50f046cefe',
    messagingSenderId: '284707235547',
    projectId: 'netflix-clone-89f02',
    storageBucket: 'netflix-clone-89f02.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0iHaFJnxeFLDRhPB6XUCqkCzjHmYKAyQ',
    appId: '1:284707235547:ios:2aba8612fbbcbc2146cefe',
    messagingSenderId: '284707235547',
    projectId: 'netflix-clone-89f02',
    storageBucket: 'netflix-clone-89f02.appspot.com',
    iosClientId: '284707235547-5fok7h4onub88buhfcslarpk9lupjlu9.apps.googleusercontent.com',
    iosBundleId: 'com.example.netflix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0iHaFJnxeFLDRhPB6XUCqkCzjHmYKAyQ',
    appId: '1:284707235547:ios:2aba8612fbbcbc2146cefe',
    messagingSenderId: '284707235547',
    projectId: 'netflix-clone-89f02',
    storageBucket: 'netflix-clone-89f02.appspot.com',
    iosClientId: '284707235547-5fok7h4onub88buhfcslarpk9lupjlu9.apps.googleusercontent.com',
    iosBundleId: 'com.example.netflix',
  );
}
